name: CustomPotions
version: 3.0
main: pe.nn.connor.custompotions.CustomPotions
commands:
    custompotions:
        description: The base command for Custom Potions
        usage: See '/<command> help'
        aliases: [cp, cpotions, customp, cupo]