name: Custom Potions
version: 3.0
main: pe.nn.custompotions.custompotions
commands:
    custompotions:
        description: The base command for Custom Potions
        usage: See '/<command> help'
        aliases: [cp, cpotions, customp, cupo]